[package]
name = "market_ws_tokenview_adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
anyhow = "1.0"