name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
    
    - name: Install Rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Build all crates
      run: |
        source $HOME/.cargo/env
        for crate in $(find . -type f -name Cargo.toml); do
          echo "Building crate: $crate"
          (cd $(dirname "$crate") && cargo build --release)
        done

    - name: Run tests
      run: |
        source $HOME/.cargo/env
        for crate in $(find . -type f -name Cargo.toml); do
          echo "Testing crate: $crate"
          (cd $(dirname "$crate") && cargo test)
        done
